/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2025-04-14 06:28:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.ServletException;

public final class addDoctor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("javax.servlet.ServletException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Add Doctor Details - Hospital Management System</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #f0f0f0;\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("        .container {\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 30px;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 600px;\n");
      out.write("        }\n");
      out.write("        h2 {\n");
      out.write("            font-size: 24px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            color: #333;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            text-align: left;\n");
      out.write("        }\n");
      out.write("        .form-group label {\n");
      out.write("            font-size: 14px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: #333;\n");
      out.write("            margin-bottom: 5px;\n");
      out.write("            display: block;\n");
      out.write("        }\n");
      out.write("        .form-group input, .form-group select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-top: 5px;\n");
      out.write("        }\n");
      out.write("        button {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 12px;\n");
      out.write("            background-color: #6c5ce7;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.3s ease;\n");
      out.write("        }\n");
      out.write("        button:hover {\n");
      out.write("            background-color: #5a4ae3;\n");
      out.write("        }\n");
      out.write("        .error {\n");
      out.write("            color: red;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h2>Add Doctor Details</h2>\n");
      out.write("        <form method=\"post\">\n");
      out.write("            <!-- Doctor Personal Info -->\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"firstName\">First Name:</label>\n");
      out.write("                <input type=\"text\" id=\"firstName\" name=\"firstName\" required placeholder=\"Enter doctor's first name\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"lastName\">Last Name:</label>\n");
      out.write("                <input type=\"text\" id=\"lastName\" name=\"lastName\" required placeholder=\"Enter doctor's last name\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"email\">Email:</label>\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"Enter doctor's email\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"contactNumber\">Contact Number:</label>\n");
      out.write("                <input type=\"text\" id=\"contactNumber\" name=\"contactNumber\" required pattern=\"\\d{10}\" placeholder=\"Enter doctor's 10-digit contact number\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Doctor's Specialty and Availability -->\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"specialty\">Specialty:</label>\n");
      out.write("                <input type=\"text\" id=\"specialty\" name=\"specialty\" required placeholder=\"Enter the doctor's specialty\">\n");
      out.write("            </div>\n");
      out.write("<!--            <div class=\"form-group\">\n");
      out.write("                <label for=\"availability\">Availability:</label>\n");
      out.write("                <input type=\"text\" id=\"availability\" name=\"availability\" required placeholder=\"Enter availability (e.g., Mon-Fri, 9am-5pm)\">\n");
      out.write("            </div>-->\n");
      out.write("\n");
      out.write("            <!-- Submit Button -->\n");
      out.write("            <button type=\"submit\" name=\"addDoctorDetails\">Save Doctor Details</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        ");
 
            // Get form data
            String firstName = request.getParameter("firstName");
            String lastName = request.getParameter("lastName");
            String email = request.getParameter("email");
            String contactNumber = request.getParameter("contactNumber");
            String specialty = request.getParameter("specialty");
           // String availability = request.getParameter("availability");

            // Initialize error message
            String errorMessage = null;

            // Check if form is submitted
            if (request.getParameter("addDoctorDetails") != null) {
                // Server-side validation
                if (firstName == null || firstName.isEmpty() ||
                    lastName == null || lastName.isEmpty() ||
                    email == null || email.isEmpty() ||
                    contactNumber == null || contactNumber.isEmpty() ||
                    specialty == null || specialty.isEmpty()) //||
                    //availability == null || availability.isEmpty()) 
                    {
                    errorMessage = "All fields are required.";
                } else if (!contactNumber.matches("\\d{10}")) {
                    errorMessage = "Contact number must be exactly 10 digits.";
                } else if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
                    errorMessage = "Invalid email format.";
                } else {
                    // If validation passes, check if the email or contact number exists in the database
                    Connection conn = null;
                    PreparedStatement stmt = null;
                    ResultSet rs = null;

                    try {
                        // Database connection
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital_db", "root", "root");
 
                        // Check if email already exists
                        String emailCheckQuery = "SELECT email FROM receptionist WHERE email = ? UNION SELECT email FROM doctor WHERE email = ?";
                        stmt = conn.prepareStatement(emailCheckQuery);
                        stmt.setString(1, email);
                        stmt.setString(2, email);
                        rs = stmt.executeQuery();
                        
                        if (rs.next()) {
                            errorMessage = "Email already exists.";
                        } else  {
                            // Check if contact number already exists
                            String phoneCheckQuery = "SELECT contact_number FROM receptionist WHERE contact_number = ? UNION SELECT contact_number FROM doctor WHERE contact_number = ?";
                            stmt = conn.prepareStatement(phoneCheckQuery);
                            stmt.setString(1, contactNumber);
                            stmt.setString(2, contactNumber);
                            rs = stmt.executeQuery();
                            
                            if (rs.next()) {
                                errorMessage = "Contact number already exists.";
                            } else {
                                // No duplicates, insert the new doctor data
                                String sql = "INSERT INTO doctor (first_name, last_name, email, contact_number, specialty) VALUES (?, ?, ?, ?, ?)";
                                stmt = conn.prepareStatement(sql);
                                stmt.setString(1, firstName);
                                stmt.setString(2, lastName);
                                stmt.setString(3, email);
                                stmt.setString(4, contactNumber);
                                stmt.setString(5, specialty);
                               // stmt.setString(6, availability);

                                int result = stmt.executeUpdate();
                                if (result > 0) {
                                    out.println("<p>Doctor details added successfully!</p>");
                                    response.sendRedirect("doctorHistory.jsp");
                                } else {
                                    errorMessage = "Error: Could not add doctor details.";
                                }
                            }
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        errorMessage = "An unexpected error occurred: " + e.getMessage();
                    } finally {
                        try {
                            if (rs != null) rs.close();
                            if (stmt != null) stmt.close();
                            if (conn != null) conn.close();
                        } catch (SQLException ignored) {}
                    }
                }
            }

            // Display error message if any validation fails
            if (errorMessage != null) {
                out.println("<p class='error'>" + errorMessage + "</p>");
            }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
